# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dVyrK8I_V07Z18ZE-pv7Odq6F_3PyiyI
"""

#operators

#conditional statement
#if ,switch,case
#if

age=19
if("age >18"):
    print("age is 19")
else:
    print("age is not 18 year")

#take 2 numbers and find greatest num
#take 3 numbers and find out greatest amongnfrom 3

num=55,76
if(76>55):
  print("number is grater")
elif(55>76):
  print("number is less")
else:
  print("number is not greater")

num=15,20,87
if(15>20):
  print("number is greater")

if(20>87):
  print("number is greater")

elif(87>15):
  print("which is grater")

#take 2 variables and chek both variables are integr so we have to perform arithmetic operations

x=10
y=15
if(type(x)is int and type(y) is int):
  print(x+y)

#take an inputb from an user chek wether the string data type or not we need to count how many vowels are are for each vowels

#take a input from user and count how many vowels are there
def count_vowels(input_str):
    vowels = "aeiouAEIOU"
    count = 0
    for char in input_str:
        if char in vowels:
            count += 1
    return count
input_str = input("Enter a string: ")
vowel_count = count_vowels(input_str)
print(f"The number of vowels in the input is: {vowel_count}")

#take a input from a user and find out how many charcter are there
text=input("enter an string")
 print(len(text))



#take a input from user and chek that integer input should be satisfied the divisibiltty rule of a number 4

number=int(input("enter an integer"))

if number % 4 ==0:
  print(f"{number}is divisible by 4")
else:
  print(f"{number} is not divisible by 4")

#take a input from user and find out wether its even number or odd number

number=int(input(" enter an integer"))
if number% 2 ==0:
  print(f"{number} is even " )
else:
  print(f"{number} is odd")

#take a input from user and extrat the last charchert of string

text=input("enter a string:")
last_character=text[-1]

print("the last character is " ,last_character)

#take a input from user and extract second word of the string

text=input("enter a string:")
second_character=text[2]

print("the second character is " ,second_character)

# Get input from the user
user_input = input("Enter a string: ")

# Check if the input is a string
if isinstance(user_input, str):
    # Initialize counters for each vowel
    vowel_counts = {'a': 0, 'e': 1, 'i': 2, 'o': 3, 'u': 4}

    # Convert the input to lowercase for case-insensitive counting
    user_input = user_input.lower()

    # Count the number of vowels
    for char in user_input:
        if char in vowel_counts:
            vowel_counts[char] += 1

    # Print the counts for each vowel
    for vowel, count in vowel_counts.items():
        print(f"Number of '{vowel}'s: {count}")
else:
    print("The input is not a string.")

from types import EllipsisType
#take 3 numbers and find out greatest amongnfrom 3

def find_greatest (num1,num2,num3):
  if num1>=num2 and num1>=num3:
    return num1
  elif num2>=num1 and num2>=num3:
    return num2
  else:
    return num3


num1 = float(input("enter the first number"))
num2 = float(input("enter the second number"))
num3 = float(input("enter the third number"))
greatest_num = find_greaest(num1,num2,num3)
print("the greatest number is:",  greatest_num)

# Function to find the largest number among three
def find_largest(num1, num2, num3):
    largest_num = max(num1, num2, num3)
    return largest_num

# Take input from the user
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
num3 = float(input("Enter the third number: "))

# Call the function and print the result
largest_num = find_largest(num1, num2, num3)
print("The largest number is:", largest_num)

